name: AutoUpdate
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # 取得完整歷史以利合併
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: pip install requests
      - name: Run Update
        run: python update_data.py
      - name: Deploy
        run: |
          git config --global user.name "Bot"
          git config --global user.email "bot@github.com"
          git add index.html
          git commit -m "Auto update data" || exit 0
          git pull --rebase origin main # 強制合併遠端變更
          git push
